all:

windows: main.cpp
	g++.exe main.cpp -I "..\..\SFML-2.5.1\include" -lsfml-system -lsfml-graphics -lsfml-window -L "..\..\SFML-2.5.1\build\lib"

mac: main.cpp
	g++ main.cpp -I "..\..\SFML-2.5.1\include" -lsfml-system -lsfml-graphics -lsfml-window -L "..\..\SFML-2.5.1\build\lib"
